### ISSUE TITLE
Problem: webpack-dev-server fails to start on `lore-quickstart`

### ISSUE THREAD

**Issue by lenards** [lore/lore#173]
In doing the initial _"lore-quickstart"_, I hit an error trying to start webpack-dev-server [in Step 3](http://www.lorejs.org/quickstart/setup/step-3/):

```
✔ ~/devel/lore-quickstart 
14:06 $ npm start 

> lore-quickstart@0.0.0 start /Users/lenards/devel/lore-quickstart
> webpack-dev-server --history-api-fallback --hot --env=development --port=3000

  build [==                  ] 10%events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lore-quickstart@0.0.0 start: `webpack-dev-server --history-api-fallback --hot --env=development --port=3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lore-quickstart@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lenards/.npm/_logs/2017-12-01T21_06_14_751Z-debug.log
```

## Version Information

I'm working on Mac OS 10.11.6 (I know, I know - I should update). 

Node & npm versions:
```
...
14:06 $ node --version 
v8.9.1
...
14:08 $ npm --version
5.5.1
```

I can include any additional version information that would be helpful. 

📝  A complete shell transcript of the commands run are included in [this Gist](https://gist.github.com/lenards/72e5c282670a2bc5e29152eac720b7e4) for context (in case I did something silly/dumb/dolt-like).

🙇

**Comment by lenards** [comment]
HA! 

Okay - I know the error for this. I have another _lore-app_ that has attached to port 3000.

**Comment by lenards** [comment]
```
14:23 $ cd lore-quickstart/
✔ ~/devel/lore-quickstart 
14:24 $ npm start 

> lore-quickstart@0.0.0 start /Users/lenards/devel/lore-quickstart
> webpack-dev-server --history-api-fallback --hot --env=development --port=3000

  build [==                  ] 10%Project is running at http://localhost:3000/
webpack output is served from /
404s will fallback to /index.html
Build completed in 6.576s

Hash: 8afc38ad9b0d36e05fff
Version: webpack 2.7.0
Time: 6579ms
```

**Comment by lenards** [comment]
_Nothing to see here!_

Closing.
